type token =
  | EOF of (Info.t)
  | MODULE of (Info.t)
  | OPEN of (Info.t)
  | OF of (Info.t)
  | TYPE of (Info.t)
  | UNIT of (Info.t)
  | BOOL of (Info.t)
  | INT of (Info.t)
  | CHAR of (Info.t)
  | STRING of (Info.t)
  | REGEXP of (Info.t)
  | AREGEXP of (Info.t)
  | SKELETONS of (Info.t)
  | RESOURCES of (Info.t)
  | LENS of (Info.t)
  | CANONIZER of (Info.t)
  | FORALL of (Info.t)
  | WHERE of (Info.t)
  | BOOLPREFS of (Info.t)
  | INTPREFS of (Info.t)
  | STRINGPREFS of (Info.t)
  | STRINGLISTPREFS of (Info.t)
  | STR of (Bident.Id.t)
  | UIDENT of (Bident.Id.t)
  | LIDENT of (Bident.Id.t)
  | QUALIDENT of (Bident.Id.t)
  | TYVARIDENT of (Bident.Id.t)
  | CSET of (Bident.Id.t)
  | NSET of (Bident.Id.t)
  | CHARACTER of (Info.t * char)
  | INTEGER of (Info.t * int)
  | BOOLEAN of (Info.t * bool)
  | CEX of (Info.t)
  | FLOAT of (Info.t * float)
  | HASH of (Info.t)
  | LBRACE of (Info.t)
  | RBRACE of (Info.t)
  | LLIST of (Info.t)
  | LBRACK of (Info.t)
  | RBRACK of (Info.t)
  | LPAREN of (Info.t)
  | RPAREN of (Info.t)
  | LANGLE of (Info.t)
  | RANGLE of (Info.t)
  | ARROW of (Info.t)
  | DARROW of (Info.t)
  | DEQARROW of (Info.t)
  | EQARROW of (Info.t)
  | BEGIN of (Info.t)
  | END of (Info.t)
  | GRAMMAR of (Info.t)
  | AND of (Info.t)
  | FUN of (Info.t)
  | LET of (Info.t)
  | IN of (Info.t)
  | TEST of (Info.t)
  | MATCH of (Info.t)
  | WITH of (Info.t)
  | SEMI of (Info.t)
  | COMMA of (Info.t)
  | DOT of (Info.t)
  | EQUAL of (Info.t)
  | COLON of (Info.t)
  | COLONCOLON of (Info.t)
  | BACKSLASH of (Info.t)
  | SLASH of (Info.t)
  | STAR of (Info.t)
  | RLUS of (Info.t)
  | BANG of (Info.t)
  | BAR of (Info.t)
  | BARBAR of (Info.t)
  | DOLLAR of (Info.t)
  | PLUS of (Info.t)
  | MINUS of (Info.t)
  | UNDERLINE of (Info.t)
  | HAT of (Info.t)
  | TILDE of (Info.t)
  | AMPERSAND of (Info.t)
  | QMARK of (Info.t)
  | LT of (Info.t)
  | GT of (Info.t)
  | LEQ of (Info.t)
  | GEQ of (Info.t)
  | STYPE of (Info.t)
  | VTYPE of (Info.t)
  | ASTYPE of (Info.t)
  | AVTYPE of (Info.t)
  | BIJ of (Info.t)
  | GET of (Info.t)
  | PUT of (Info.t)
  | CREATE of (Info.t)
  | CANONIZE of (Info.t)
  | CHOOSE of (Info.t)
  | INTO of (Info.t)
  | ERROR of (Info.t)

val modl :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> Bsyntax.modl
val uid :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> Bident.Qid.t
val qid :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> Bident.Qid.t
